jobs:

  - name: dks-app-def
    type: manifest
    steps:
      - IN: dks_app_img
      - TASK: managed

  # Job that provisions the GKE cluster
  - name: create_secret
    type: runSh
    steps:
      - IN: dks_gitRepo
        # manually trigger the cluster provisioning job and not on every
        # commit to the repository
        switch: off
      - IN: dks_kube_cliConfig
      - IN: dks-app-def
      - IN: dks_secrets
      - TASK:
        # invoke a script that provisions the GKE cluster named test-cluster
        - script: |
            pushd $(shipctl get_resource_state "dks_gitRepo")/kubernetes-secrets
              # Replace placeholders in the secret yml with environment variables
              # injected by the key-value pair integration
              shipctl replace ./create-secret.yml
              cat ./create-secret.yml

              # Delete and create the secret
              kubectl delete secret shipsecret 2>/dev/null || echo "secret does not exist"
              kubectl create -f ./create-secret.yml
            popd

  - name: dks-app-deploy
    type: deploy
    method: replace
    steps:
      - IN: create_secret
      - IN: dks_secret_opts
      - IN: dks-app-def
        switch: off
      - IN: dks_kube_cluster

  - name: dks-provision-lb
    type: provision
    steps:
      - IN: dks_lb
