jobs:

  - name: dks-app-def
    type: manifest
    steps:
      - IN: dks_app_img
      - TASK: managed

  - name: dks-provision-lb
    type: provision
    steps:
      - IN: dks_lb

  - name: dks-app-deploy
    type: deploy
    method: replace
    steps:
      - IN: dks_opts
      - IN: dks-app-def
      - IN: dks_kube_cluster
